### ISSUE TITLE
onInstallConversionDataLoaded no work in ios

### ISSUE THREAD

**Issue by af-fess** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#1]
migrated from old PhoneGap:

@WilsonFpz

_Hi
I have a same ionic app publish in appstore/android.
The onInstallConversionDataLoaded attributionData works fine for an android user.
But when an iphone user shows no data._
```
document.addEventListener('onInstallConversionDataLoaded', function(e){ var attributionData = (JSON.stringify(e.detail)); $localStorage.trackingData = attributionData; }, false);
any ideas? thanks
```

**Comment by af-fess** [comment]
@af-fess

@WilsonFpz did you try to debug:
-(void)onConversionDataReceived:(NSDictionary*) installData {/*...*/} line 116. inside AppsFlyerPlugin.m ? Please let me know

Also please, post relevant code snippets

**Comment by af-fess** [comment]
@lalmanzar 

@af-fess _I have an issue with the onInstallConversionDataLoaded on ios. It is always reporting as organic. But on the dashboard is tracked correctly as a non-organic and all the other fields like the campaign, also on the raw install export is reported correctly. The issue is only with ios, android is reported correctly. Any idea what might be the issue?
Thanks_

**Comment by af-fess** [comment]
@af-fess

_@lalmanzar it looks weird, how did you test non-organic install, please give more details._

**Comment by af-fess** [comment]
@lalmanzar

In the config.xml I have:
`<plugin name="appsflyer" version="4.2.8"/>`
in my main.js I have this inside the device ready:
`var args = {
        devKey: 'aanexxxxxxxxxxxxxxxxxxxxxxxx'
    };`
    `var userAgent = window.navigator.userAgent.toLowerCase();`
   ` if (/iphone|ipad|ipod/.test( userAgent )) {`
   `     args.appId = "id11111111111";           `
  `  }`
 `   window.plugins.appsFlyer.initSdk(args);`

and this at the end:
`document.addEventListener('onInstallConversionDataLoaded', function(e){`
 `   var attributionData = e.detail;`
`    alert(JSON.stringify(attributionData));`
`}, false);`

Then I build the app using phonegap Build (I don't have a ios machine to do the build).
For the steps I use for testing, I first click the custom like I have with a campaing and some extra parameters that I'll need, after that I install the IPA and open the app. In the dashboard I can see the click and install of the custom campaing but the app shows this in the alert :
`{"af_status":"Organic","af_message":"organic install"}`

I also tried with the sdk of the new repository and have the same issue.

Is there a way for me to check if maybe the plugin is having issues to get the IDFA of the device?

**Comment by lalmanzar** [comment]
@af-fess found my issue, in the appId I left the "id" part. I should only be the number part. Thanks

**Comment by quyen91** [comment]
Thank @lalmanzar , I have same issues. My appId for test is: `id012345`, I only need remove `id` and now xcode log it as non-organic install. `options: { appId: "012345" }`

**Comment by quynt8313** [comment]
> Thank @lalmanzar , I have same issues. My appId for test is: `id012345`, I only need remove `id` and now xcode log it as non-organic install. `options: { appId: "012345" }`

thanks you so much, save my day !!!!

**Comment by theb205** [comment]
> Thank @lalmanzar , I have same issues. My appId for test is: `id012345`, I only need remove `id` and now xcode log it as non-organic install. `options: { appId: "012345" }`

you are my hero man, Good job @quyen91
