### ISSUE TITLE
Cannot check trackingEvent

### ISSUE THREAD

**Issue by MathiewNguyen** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#10]
Hi,

I'm using this plugin with angularjs to trackingEvent but I canot see event on Dashboard.

This is my code:

        var onSuccess = function (result) {
            console.log("onSuccess init sdk");

            var eventName = "Main Screen";
            var params = {
                "af_content_id": "id123",
                "af_currency": "USD",
                "af_revenue": "2"
            };
            $window.plugins.appsFlyer.trackEvent(eventName, params);

        };

        function onError(err) {
            console.log("onError init sdk");
        }

        var options = {
            devKey: 'devkey',
            isDebug: false,
            onInstallConversionDataListener: true
        };
        $window.plugins.appsFlyer.initSdk(options, onSuccess, onError);

I cannot see the event on Dashboard event, image as below:

![aaas](https://cloud.githubusercontent.com/assets/28383516/25692905/269d5f7a-30d0-11e7-8655-d69d710f6439.png)

Does my source code missing anything? Do I need setting anything?
Please help me this case.

Thanks.

**Comment by BenjaminAF** [comment]
Hello,

As this issue requires sharing of private / sensitive information that should't be exposed to all, could you please migrate this to our official channel at support@appsflyer.com

When submitting this issue please specify your AppsFlyer sign-up (account) email , your app ID , production environment (iOS? Android?), logs, code snippets and any additional relevant information.

**Comment by 6ewis** [comment]
What was the issue?
