### ISSUE TITLE
Appsflyer plugin.xml is v4.2.18, should be 4.2.19?

### ISSUE THREAD

**Issue by fephil** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#12]
Hi,

When installing the plugin using Cordova 6.5.0 or 7.0.1, version 4.2.18 is installed and not the latest version. Even if i specifically include 4.2.19, the wrong version is installed. Could you bump the plugin.xml?

Thanks.

**Comment by af-fess** [comment]
fixed, tnx
