### ISSUE TITLE
Uncaught TypeError: e.plugins.appsFlyer.setGCMProjectID is not a function

### ISSUE THREAD

**Issue by koenoe** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#13]
Cordova version: 6.5.0
Plugin version: 4.2.19

If I look at the source it looks like this method is renamed to 'setGCMProjectNumber'. Please update documentation or change it back to 'setGCMProjectID' so it's backwards compatible.

**Comment by af-fess** [comment]
`setGCMProjectNumber` API was removed and replaced with `enableUninstallTracking`
