### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dasMajo** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#18]
# Error
**Invalid type in JSON write (NSURLError)**

# Stack Trace
`Fatal Exception: NSInvalidArgumentException`
`0  CoreFoundation                 0x1e153b3d __exceptionPreprocess`
`1  libobjc.A.dylib                0x1d3db067 objc_exception_throw`
`2  CoreFoundation                 0x1e153a85 -[NSException initWithCoder:]`
`3  Foundation                     0x1eb1585b (Missing)`
`4  Foundation                     0x1eb176e9 (Missing)`
`5  CoreFoundation                 0x1e0bb2fd __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke`
`6  CoreFoundation                 0x1e0ac77f -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]`
`7  Foundation                     0x1eb16f5f (Missing)`
`8  Foundation                     0x1eb1579b (Missing)`
`9  Foundation                     0x1eb1559f (Missing)`
`10 Foundation                     0x1eb1641b (Missing)`
`11 AppName                        0x4594b -[AppsFlyerPlugin handleCallback:] (AppsFlyerPlugin.m:192)`

# Description
The Plugin tries to serialize an NSError reported from the AppsFlyerDelegate via NSJSONSerialization, which results in a crash. Either `onConversionDataRequestFailure` or `onAppOpenAttributionFailure` can cause this.

# Solution
See Pull Request

**Comment by orangeappsgames** [comment]
I have same issue.
```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x24759b0b __exceptionPreprocess
1  libobjc.A.dylib                0x23f16dff objc_exception_throw
2  CoreFoundation                 0x24759a51 -[NSException initWithCoder:]
3  Foundation                     0x24ff480d _writeJSONValue
4  Foundation                     0x24ff672b ___writeJSONObject_block_invoke
5  CoreFoundation                 0x246c3cb5 __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke
6  CoreFoundation                 0x246b49ff -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]
7  Foundation                     0x24ff5f4d _writeJSONObject
8  Foundation                     0x24ff4741 _writeJSONValue
9  Foundation                     0x24ff4553 -[_NSJSONWriter dataWithRootObject:options:error:]
10 Foundation                     0x24ff540d +[NSJSONSerialization dataWithJSONObject:options:error:]
11 Candy Valley                   0xe9491 -[AppsFlyerPlugin handleCallback:] (AppsFlyerPlugin.m:229)
12 Foundation                     0x24f86887 __NSThreadPerformPerform
13 CoreFoundation                 0x2471b9e7 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
14 CoreFoundation                 0x2471b5d7 __CFRunLoopDoSources0
15 CoreFoundation                 0x2471993f __CFRunLoopRun
16 CoreFoundation                 0x246681c9 CFRunLoopRunSpecific
17 CoreFoundation                 0x24667fbd CFRunLoopRunInMode
18 GraphicsServices               0x25c84af9 GSEventRunModal
19 UIKit                          0x28da0435 UIApplicationMain
20 Candy Valley                   0xb63b3 main (main.m:32)
21 libdispatch.dylib              0x24314873 (Missing)
```
