### ISSUE TITLE
Feature Request: Plugin support for `onConversionDataReceived`

### ISSUE THREAD

**Issue by gylippus** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#20]
Thank you for providing this valuable plugin. Would it be possible to add support for `onConversionDataReceived`?

We'd like to be able to track this campaign information for installs in our own system as well. 

It appears some support is enabled in the `AppsFlyerPlugin.m`, but not in the plugin's js. I tried to add it on my own but I was running into a lot of native errors on a Main.m file after that.

**Comment by af-fess** [comment]
@gylippus hi, please take a look on example: https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/master/examples/demoA/www/js/AppsFlyer/AfController.js#L98. 

You can provide `onInstallConversionDataListener: true` and you will get `onGetConversionDataReceived` callback as 2nd parameter of `initSdk`. 

See: https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/master/examples/demoA/www/js/AppsFlyer/AfController.js#L108-L124
