### ISSUE TITLE
enableUninstallTracking feature not working on iOS platform

### ISSUE THREAD

**Issue by nexussmart** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#25]
Hi, 

We try to use the **enableUninstallTracking** feature. It's work fine on Android (we received tracking on the dashboard) but not for the iOS part.

After a deeper look inside iOS plugin part : https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/master/src/ios/AppsFlyerPlugin.m :

We found out that the **registerUninstall** function not being called in the cordova/javascript part of the plugin at https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/master/www/appsflyer.js

Thanks

**Comment by langkunye** [comment]
@nexussmart 
`We try to use the enableUninstallTracking feature. It's work fine on Android (we received tracking on the dashboard) but not for the iOS part.`

Hi!
I want try use the **enableUninstallTracking**  feature  to work on android and receive track on the dashboard, Could you tell me how to did it? thanks
