### ISSUE TITLE
iOS Univeral Links not directing to deeplink url

### ISSUE THREAD

**Issue by TMMeijers** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#29]
Following the setup for this cordova project as well as enabling universal links for iOS does not result in actually directing a user to a specific page in our app.

Versions: 
```
cordova 7.1.0
cordova-android 6.4.0
cordova-ios 4.5.3
cordova-plugin-appsflyer-sdk 4.3.0
iOS: 10.3.3
```

The associated domains is set to `applinks:triggi.onelink.me`, we then publish a onelink with a deep link into a specific page in our app. 

On Android the normal deeplinks work, e.g. `handleOpenUrl` is called, we call `appsflyer.handleOpenUrl` and we then continue to route into the app to the page requested in the deeplink.

However, on iOS it does open our app when it is installed but `handleOpenUrl` is never called. I cannot find any other part mentioning a different handling of universal links in the documentation. As the app is opened, universal links must be configured correctly. How to proceed from here?

**Comment by amrayoub** [comment]
you have to set it up in associated domains in Xcode
check here
https://support.appsflyer.com/hc/en-us/articles/207032266-Setting-Deeplinking-on-iOS9-using-iOS-Universal-Links

**Comment by TMMeijers** [comment]
I received a reply on SO: https://stackoverflow.com/questions/48342732/appsflyer-universal-links-ios-not-routing-to-requested-page/48368428#48368428

The deeplink contained in the onelink is passed through `appsflyer.initSdk` in the success callback. The original onelink through which the app was opened is contained in `data.link` in the info passed through that callback.
