### ISSUE TITLE
App Open Attribution Data not Always Reported on iOS

### ISSUE THREAD

**Issue by KamenGoranchev** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#30]
After we noticed missing app open attribution data for some of our users we had a deeper look at the source of the pluggin to search for a reason - and we found it:

We are setting `onInstallConversionDataListener` to `true` when initializing the SDK to receive the appropriate callbacks.  Nevertheless, the `onSuccess` callback is not called in all cases with the attribution data. The reason for this is the way the native callbacks (`onConversionDataReceived` & `onAppOpenAttribution`) are handled in `AppsFlyerPlugin.m`.
When starting the app with an AppsFlyer deep link, we should receive both the conversion data (native: `onConversionDataReceived`) and the deep link information (native: `onAppOpenAttribution`). The problem in the plugin implementation is that only the first of these two callbacks is forwarded to the Java script part of the code and the one that comes second is ignored, because the `conversionListeners` will be set to null after the first `onSuccess` call (`AppsFlyerPlugin.m` line 386,  394 and 375). 

Our observation shows that the native callbacks `onConversionDataReceived` & `onAppOpenAttribution` are both called correctly when we open the app from a deep link, but they are called in different sequence depending if the app is in background or not. This leads to the result that if you open the app with a deeplink, only the conversion data is sent into JavaScript with `onSuccess` callback in the case the app was not running at all, and only the app open attribution data is sent in the case the app was in background (app resumes).
The correct behaviour would be, that both the `onConversionDataReceived` & `onAppOpenAttribution` should be forwarded in both cases.

Keeping the `conversionListeners` (=not setting to null in line 386, 394 and maybe also 375) seems to solve the problem, but we don't know the reason why these listeners are currently being removed after their first call.
As this problem affects all users of the Cordova AppsFlyer plugin, it would be good to solve this asap so that deep link attribution can work.

**Comment by a0rthur0** [comment]
Same for us, but with Android

**Comment by sebaferreras** [comment]
> As this problem affects all users of the Cordova AppsFlyer plugin, it would be good to solve this asap so that deep link attribution can work.

The same is happening to us, for both Android and iOS. So for example, 

1. If I click on a link (which takes me to the Play Store) and then install the app via `ionic cordova run android --prod`, I see the following data:

    ![install](https://user-images.githubusercontent.com/17194770/42223299-c01ff788-7ed7-11e8-9b9c-5c52f4e59ff6.jpeg)

    **This seems to be working fine (*)**

    (*) Most of the times I need to execute the `initSdk` function twice to get the response from the AppsFlyer SDK, but that's **[another issue](https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/issues/34)**

2. If instead, I click on a link having the app already installed, I get the same data (containing the `onInstallConversionDataLoaded`):

    ![install](https://user-images.githubusercontent.com/17194770/42223299-c01ff788-7ed7-11e8-9b9c-5c52f4e59ff6.jpeg)


    But if I call the `initSdk` function again, I get the deep link data now:

    ![deep link](https://user-images.githubusercontent.com/17194770/42223851-0b473bd0-7ed9-11e8-98a8-a0f74bc566f2.jpeg)

-----
So just like @KamenGoranchev mentions, we should get both details when calling the `initSdk` method instead of calling it several times to see if this should be treated as a deep link or as a new install, right?

I must say that I'm kind of surprised that this issue was opened 4 months ago and there's no answer yet because it affects the way deep link attribution works, which is one of the main goals of AppsFlyer.

@af-fess what would you recommend for this issue?

**Comment by af-fess** [comment]
@sebaferreras thank you for detailed use case. Will be fixed and published in next week

**Comment by dilanfdo** [comment]
@af-fess onAppOpenAttribution method is not available on the plugin(appsflyer.js) for us to implement it on our app.
