### ISSUE TITLE
invalid JSON in initSdk's onSuccess callback on link click

### ISSUE THREAD

**Issue by deumax** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#31]
Hi,

I am using version 4.3.0 with ionic 3 and cordova android 6.3.0

`this.appsFlyer.initSdk(options,
      successData => {
        console.log(successData);
      },
      error => {
        console.log('AppsFlyer:initSdk error: ', error);
      }
   );`

Invalid JSON (without quotes) output after i clicked a OneLink:
`{af_deeplink=true, campaign=testcampaign, media_source=test, install_time=2018-02-19 10:33:48, af_status=Non-organic, path=, scheme=myscheme, host=myhost}`

Just opening the App gives me a correct JSON:

`{"status":"success","type":"onInstallConversionDataLoaded","data":{"af_message":"organic install","af_status":"Organic"}}`

Is this fixed in a newer version? It is currently not possible to upgrade to 4.4 due to not being able to upgrade cordova from 6 to 7.

Thanks

**Comment by malua** [comment]
Still happening in Version 4.4.7!

**Comment by af-fess** [comment]
fixed in 4.7.8
