### ISSUE TITLE
onAppOpenAttribution never reported on first boot of app

### ISSUE THREAD

**Issue by Gurrt** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#34]
Our issues looks somewhat similar to #30 however in our case onAppOpenAttribution is not called at the very first boot of the app, subsequent times the app is started the callback returns just fine.

This is an issue for us because we rely on AppsFlyer to give us this data to present user-specific data precisely at first boot. Is there any way around this?

**Comment by Gurrt** [comment]
A workaround that works for us is to call the `InitSDK` function twice. We would love to see a proper fix though.

**Comment by sebaferreras** [comment]
I can confirm this is happening both on Android and iOS

**Comment by aznj** [comment]
this is still happening in android especially after app killed
