### ISSUE TITLE
Android: warning on missing ACCESS_WIFI_STATE permission

### ISSUE THREAD

**Issue by davidefavia** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#4]
Hi,
I'm testing plugin integration with a Cordova application. I activated debug mode (`isDebug: true`) in Android simulator and the application logs:

```
W/AppsFlyer_4.6.1: Permission android.permission.ACCESS_WIFI_STATE is missing in the AndroidManifest.xml
```

and effectively the requested permission is missing in the manifest. However I do not found the permission config inside the plugin.xml file (as seen [here](https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/249d13a9f45e6b678180db8cbcb3888054af30aa/plugin.xml#L52)).

```
<config-file target="AndroidManifest.xml" parent="/manifest">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
</config-file>
```

It should be added or it can be omitted without any problem?

**Comment by af-fess** [comment]
@davidefavia hey, It should't break the plugin, anyways you can add this permission to your application, not as a part of this plugin. Please let me know if you have any trouble

**Comment by davidefavia** [comment]
Hi @af-fess,
thanks for your feedback. The plugin works as expected, but I don't think this issue should be closed. I surely can add the permission to the application manifest (but at the moment I can't because I create the Cordova `platforms` folder at build time), but if the plugin warns for it, I think it should be added. I'm creating a pull request for it, let me know if it is ok for you to accept external contributions or not.
