### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by jsalopez** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#46]
Hello everybody,

I have this error when I try to compile the project with Android
**_"09-05 10:43:01.202 27636-27772/com.homepaq W/System.err: java.lang.ClassNotFoundException: com.appsflyer.cordova.plugin.AppsFlyerPlugin
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
09-05 10:43:01.208 27636-27772/com.homepaq W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appsflyer.cordova.plugin.AppsFlyerPlugin" on path: DexPathList[[zip file "/data/app/com.homepaq-DRo61prvRC8Mkx2qSuEImg==/base.apk"],nativeLibraryDirectories=[/data/app/com.homepaq-DRo61prvRC8Mkx2qSuEImg==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-05 10:43:01.211 27636-27772/com.homepaq I/System.out: Error adding plugin com.appsflyer.cordova.plugin.AppsFlyerPlugin."_**

I have Cordova v8.0.0 and cordovaAndroid v6.2.3
and the last version of AppsFlyer

**Comment by jsalopez** [comment]
I try with AppsFlyer v4.3.3 and cordovaAndroid v6.2.3 because I read this:
"Important! 
Cordova AppsFlyer plugin version 4.4.0 and higher are meant to be used with cordova-android@7.0.0 
For lower versions of cordova-android please use plugin version 4.3.3 available @ https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/tree/4.3.3"

**Comment by werewolfjak** [comment]
Hi @jsalopez ,

Thanks for bringing this to our attention. Can you reach out to us via support@appsflyer.com. We'd be happy to assist you in finding the issue and getting this resolved.

Happy Friday!

**Comment by af-fess** [comment]
Hi @jsalopez , You have latest `cordova` version, `8.0.0` and old `cordova-android 6.2.3`.

As you know `cordova-android 7.x.x` has braken changes with path, see [announcements here](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html). 

For that reason we have legacy branch [4.3.3](https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/tree/4.3.3)


See the difference here: https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/4.3.3/plugin.xml#L64-L67

What is your target directory, `app/src/` or `src/`?

**Comment by af-fess** [comment]
credit card closed because of inactivity.
