### ISSUE TITLE
Ionic 4 Cordova 8

### ISSUE THREAD

**Issue by kaoecoito** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#47]
Hi, 

I'm trying to run calls using Ionic 4 with Cordova 8.0, when I run the initSdk call it does not return success or failure response. 

Even passing the debug parameter does not get any detail of where the problem is. I tested using the Android emulator and also installing directly on the device in both cases running Android 8. 

This plugin is compatible with this specification below?

========================================================
Ionic:

   ionic (Ionic CLI)  : 4.0.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.3.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.4 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.18

**Comment by paulstelzer** [comment]
You are not using Ionic 4, you are still at ionic-angular 3 (Ionic 4 ist `@ionic/angular`). You are only using the Ionic CLI 4. But that's off topic ;)

For your question: For me it's working without problems. I used Appsflyer with Ionic 3 (like you) and also using it with Ionic 4! So it should work for you too

Maybe take a look at my Angular Package -> https://github.com/paulstelzer/innomobile-library/blob/master/libs/%40innomobile/attribution/src/lib/appsflyer/appsflyer.service.ts
