### ISSUE TITLE
cordova-plugin-appsflyer-sdk@4.3.3 notarget

### ISSUE THREAD

**Issue by nexussmart** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#48]
Hello,

When i would to install 4.3.3 version like you mentioned on the important readme, the npm response is
"  
npm ERR! notarget 4.4.9, 4.4.8, 4.4.7, 4.4.6, 4.4.5, 4.4.3, 4.4.2, 4.4.0, 4.3.0, 4.2.28, 4.2.27, 4.2.25, 4.2.24, 4.2.23, 4.2.22, 4.2.21, 4.2.20, 4.2.19, 4.2.18, 4.2.17, 4.2.16, 4.2.15, 4.2.14, 4.2.13, 4.2.12, 4.2.11, 4.2.10, 4.2.9
"

Could you fixed this ?
Thank's a lot
Best,

**Comment by af-fess** [comment]
@nexussmart please post command you try to run. Thanks

**Comment by nexussmart** [comment]
ionic cordova plugin add cordova-plugin-appsflyer-sdk@4.3.3

npm ERR! notarget No compatible version found: cordova-plugin-appsflyer-sdk@4.3.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 4.4.11, 4.4.10, 4.4.9, 4.4.8, 4.4.7, 4.4.6, 4.4.5, 4.4.3, 4.4.2, 4.4.0, 4.3.0, 4.2.28, 4.2.27, 4.2.25, 4.2.24, 4.2.23, 4.2.22, 4.2.21, 4.2.20, 4.2.19, 4.2.18, 4.2.17, 4.2.16, 4.2.15, 4.2.14, 4.2.13, 4.2.12, 4.2.11, 4.2.10, 4.2.9

**Comment by gonzaloserrano** [comment]
Hi, I'm not using ionic but cordova but maybe something like would work:

`ionic cordova plugin add https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk\#4.3.3`

**Comment by esmiralhaibm** [comment]
Any chance of publishing version 4.3.3 to npm?

**Comment by af-fess** [comment]
@gonzaloserrano will be done on Sunday next week

**Comment by Matrosskin** [comment]
Is there some problem with publishing the version? Possibly we can use some other version? for example 4.3.0? But base on release notes for branch 4.3.3 and for tag 4.4.0 I am not sure if it is safe to use version 4.3.0.

**Comment by leicazetisky** [comment]
Hi, I'm having the same issue, 4.3.3 isn't on npm so I can't install it. @af-fess according to your comment this was supposed to be fixed by now, when will this actually be fixed?

**Comment by lolosett** [comment]
When will 4.3.3 be published to NPM? I'm unable to install it, and need it for a specific feature. Do you have any idea when 4.3.0 will be pushed up to NPM?

**Comment by af-fess** [comment]
I published old version `4.3.3`: https://www.npmjs.com/package/cordova-plugin-appsflyer-sdk/v/4.3.3

Keep in mind that I cannot release the old version with tag `4.3.3` because of valid SemVer restrictions. So this branch has 2 tags `4.3.3` and `old4.3.3`

**Comment by Matrosskin** [comment]
@af-fess Thank you very much!
