### ISSUE TITLE
userParams ignored on generateInviteLink

### ISSUE THREAD

**Issue by diego-carrera** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#54]
According to the documentation, when trying to pass custom data on an invite link this should be the object used.

```JS
var inviteOptions = {
  channel: "gmail",
  campaign: "myCampaign",
  customerID: "1234",
  userParams: {
    myParam : "newUser",
    anotherParam : "fromWeb",
    amount : 1
  }
};
```

The link is created successfully, and when opened on the application, and reading the data with 
```registerOnAppOpenAttribution``` the data is missing the custom parameters.

On IOS

https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/c09949981dc3bfbc142e5abbf4ea9261a024dc75/src/ios/AppsFlyerPlugin.m#L212-L214

On Android
https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/c09949981dc3bfbc142e5abbf4ea9261a024dc75/src/android/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java#L550

Apparently the function to generate the invite links expects the custom params on a second argument, and the plugin is only proxying one argument.

https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/c09949981dc3bfbc142e5abbf4ea9261a024dc75/www/appsflyer.js#L120-L123

**Comment by wesfieldj** [comment]
@diego-carrera Thanks for pointing that out. Solved in 4.4.16.
