### ISSUE TITLE
Deeplink not working for Facebook ads

### ISSUE THREAD

**Issue by ummerakbar45** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#58]
Hi
Appsflyer deep links in Facebook app (Ads) doesn’t work for us. 
The error message we get is below:

*App links Field Invalid:: The described URL doesn’t have app links HTML meta tags. Use a different URL or a mobile deep link(e.g ‘mobile app://).*

**Comment by M-Khay** [comment]
I have a similar issue. I'm generating firebase dynamic link on firebase console and when I try to put it in FB Ad's it gives me the same error" App Links Field Invalid:: The described URL doesn't have app links HTML meta tags. Use a different URL or a mobile deep link (eg 'mobileapp://). (#1487904)"

**Comment by jgersindemir** [comment]
Same situation :  firebase dynamic link on firebase console and when I try to put it in FB Ad's it gives me the same error" App Links Field Invalid:: The described URL doesn't have app links HTML meta tags. Use a different URL or a mobile deep link (eg 'mobileapp://). (#1487904)"
Any solution ?

**Comment by iranaahsanali** [comment]
I have a similar issue. I'm generating firebase dynamic link on firebase console and when I try to put it in FB Ad's it gives me the same error" App Links Field Invalid:: The described URL doesn't have app links HTML meta tags. Use a different URL or a mobile deep link.

**Comment by AndrewMorsillo** [comment]
Anybody get this working? Dynamic links seem to always be rejected by Facebook for now having app links fields.

**Comment by libinvbabu** [comment]
Same issue. Any solution?

**Comment by ahamdy96** [comment]
Same issue here as well, anyone got this working?

**Comment by ayuzovNCG** [comment]
Same issue here. Can't use Onelink for deeplink field for Traffic campaign in FB. Getting same error.

**Comment by msvargas** [comment]
Hi @ummerakbar45, did you figure it out this? thanks

**Comment by dilip-jaiswal** [comment]
Same issues here. anyone has fixed this? anyone got this working?

**Comment by arun-web-dev** [comment]
Same issues here. anyone has fixed this? anyone got this working?
