### ISSUE TITLE
Cannot track events with no recommended values on Android

### ISSUE THREAD

**Issue by davidefavia** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#6]
Hi,
I tried to track event `af_login` on both iOS and Android platforms. I had no problem with iOS platform while I encountered some issues with Android.
I can't track the event with these calls on Android:

```
window.plugins.appsFlyer.trackEvent("af_login"); // Cannot track: I'm fine with it, one parameter is missing
window.plugins.appsFlyer.trackEvent("af_login", null); // Cannot track, error
window.plugins.appsFlyer.trackEvent("af_login", undefined); // Cannot track, error
window.plugins.appsFlyer.trackEvent("af_login", {}); // Cannot track BUT no error
```

I can only track the event if I pass an object as second parameter, with one generic key (_e.g._ `af_param_1`)

```
window.plugins.appsFlyer.trackEvent("af_login", {"af_param_1":"true"}); // Tracking event is OK
```

This behaviour is the same with other events with no recommended values (_e.g._ `af_list_view`) as documented in [Android Rich In-App Events - Descriptions](https://support.appsflyer.com/hc/en-us/articles/207551843#af_login). The Android platform behaviour is not consistent with iOS one, should it be fixed?

### Additional info

AppsFlyer Android SDK version: `4.6.1`
AppsFlyer iOS SDK version: `4.5.12`

**Comment by af-fess** [comment]
@davidefavia thanks, fixed in 4.2.15
