### ISSUE TITLE
Android uninstall tracking - updateServerUninstallToken called on main thread

### ISSUE THREAD

**Issue by rammie** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#65]
Calling updateServerUninstallToken generates the following warning in the debug log:

```
THREAD WARNING: exec() call to AppsFlyerPlugin.updateServerUninstallToken blocked the main thread for 104ms. Plugin should use CordovaInterface.getThreadPool().
```

It seems like a rather long time to block the main thread. This stackoverflow post shows how to run it on a different thread https://stackoverflow.com/a/30145728 by wrapping it in `cordova.getThreadPool().execute(new Runnable() {...}`.

**Comment by wesfieldj** [comment]
@rammie fixed in v4.4.18
