### ISSUE TITLE
Ionic 3 - Cannot find module './util/default-engines'

### ISSUE THREAD

**Issue by vforvasquez** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#68]
Hi all, I tried installing with 
`ionic cordova plugin add cordova-plugin-appsflyer-sdk --save` for an ionic 3 app (currently working on the android version if that helps any) 
and I got the error:
"UnhandledPromiseRejectionWarning: Error: Cannot find module './util/default-engines'"

any help would be apprecaited!
Thanks

**Comment by af-fess** [comment]
hey @vforvasquez I don't think it is somehow related to the plugin
