### ISSUE TITLE
Deeplinks not working on device ios 

### ISSUE THREAD

**Issue by YaroslavG** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#71]
Hi, 
I include this plugin and set up deep links on both platform and it not working on real device ios, but working on simulator. What I do wrong?

Versions:
ionic 4
cordova 7.1.0
cordova-ios 4.5.5
cordova-plugin-appsflyer-sdk 4.4.15
iOS: 12.3.1

**Comment by wesfieldj** [comment]
@YaroslavG what link are you using? and what is configured in your .entitlements file?

Your .entitlements should look something like :
```
<dict>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>appslinks:test.onelink.me</string>
	</array>
</dict>
```

Also when clicking the link try to do so on a supported platform like mail/gmail or notes.

**Comment by YaroslavG** [comment]
thanks for your answer.
For example my link is: appslinks:2meet.onelink.me. 
My .entitlements is:
<dict>
    <key>com.apple.developer.associated-domains</key>
    <array>
        <string>applinks:2meet.onelink.me</string>
    </array>
</dict>
And screenshoot from my notes when I tapping on the link:
![Skype_Picture_2019_07_03T07_18_41_460Z](https://user-images.githubusercontent.com/5793103/60571325-14ae8d00-9d7c-11e9-9426-6b9abf31c5ac.jpeg)

**Comment by wesfieldj** [comment]
@YaroslavG 

First, your configuration and link look fine so it should work.

You should see in notes 'Open in 2Meet' or the app should open directly. 

Can you try to test it on a fresh device? 
Or try to uninstall all instances of the app on the device and run the test again. 

If that does not work please open a ticket to the AppsFlyer support team by emailing support@appsflyer.com. They will be able to help you more directly. 

Thanks!

**Comment by YaroslavG** [comment]
nothing helps (rebut device and uninstall/install app), turned in support, thanks

**Comment by YaroslavG** [comment]
Upd:
Deep Link does not work when I install app from link with distribution profile, when I run it from xcode I see Open In "MyApp" from notes

**Comment by YaroslavG** [comment]
issue solved, 
the same problem  [here](https://forums.developer.apple.com/thread/109479)
