### ISSUE TITLE
Get attribution Link

### ISSUE THREAD

**Issue by EmiCarrizo** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#73]
Hello, 
There is a way to get the attribution link in Android? Not the install referrer.
Was looking at #37 but wasn't able to get the link.
Am i missing something?

Cheers

**Comment by af-vs** [comment]
Hi @EmiCarrizo !

Details of the link that install was attributed to can be retrieved from `onConversionDataLoaded() `[callback method](https://support.appsflyer.com/hc/en-us/articles/207032096-Deferred-Deep-Linking-Getting-the-Conversion-Data#sdk-implementation-sdk-implementation).

Please be aware of [re-attribution window](https://support.appsflyer.com/hc/en-us/articles/115002587066-Re-Attribution-Window) causing re-installs to be not attributed. When testing, please make sure to [whitelist your device](https://support.appsflyer.com/hc/en-us/articles/207031996--Whitelisting-a-Test-Device).

We recommend following steps in [this article](https://support.appsflyer.com/hc/en-us/articles/360001559405-Testing-AppsFlyer-SDK-Integration#tests-using-attribution-links-testing-install-attribution) to test non-organic installs.

**Comment by wesfieldj** [comment]
You can get the attribution link parameters via deferred deep linking. You can see the guide to do that [here](https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/blob/master/docs/Guides.md#-1-deferred-deep-linking-get-conversion-data).

Also, check out the AppsFlyer docs on deferred deep linking [here](https://support.appsflyer.com/hc/en-us/articles/207032096-Deferred-Deep-Linking-Getting-the-Conversion-Data#Examples)

Just remember when testing deferred deep linking you need to generate a non-organic install first (or else there the API will return an organic response.)

**Comment by EmiCarrizo** [comment]
Thank you @af-vs and @wesfieldj ! I could figure it out.
Closing this issue.
