### ISSUE TITLE
Installation gives black screen

### ISSUE THREAD

**Issue by vundurty** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#9]
Hi,
Thank you so much for the plugin. I hope it works for everyone. I built an android app with Cordova CLI. I installed the plugin. After integrating the plugin, the app gives nothing but a black screen. I tried removing the plugin. After removing, the app works normally. I even tried with Phonegap build. It gives the same output. 

I installed using CLI - cordova plugin add cordova-plugin-appsflyer-sdk. It is successfully installed. 

Gradle - 3.3
Cordova cli-6.5.0

Did I miss anything? 

Please help.

**Comment by af-fess** [comment]
@vundurty hi, do you get any errors/warnings?

**Comment by vundurty** [comment]
@af-fess No, its just a blank screen. I ran the app in debug mode as well. I did't receive any error messages. At the beginning I thought it was Phonegap build error and posted it here with screenshots 'https://forums.adobe.com/thread/2291630' but accidentally I found that by removing the plugin the app works normally. 

I even tired the same with Cordova CLI build. Same thing is happening.

**Comment by BenjaminAF** [comment]
Hi vundurty, thank you for sharing that.

AppsFlyer Engineering team tried to reproduce the issue according to the information you provided, but without success (Everything worked as expected), we would be happy to continue this discussion over our support channel at support@appsflyer.com

Please provide a reference to this discussion and I'm sure we will be able to resolve that.
Best Regards.

**Comment by vundurty** [comment]
@BenjaminAF Hi, thanks for responding. Yes, I submitted ticket at your support channel. I hope the issue will be resolved soon.
